In [4]:
import sys

!{sys.executable} -m pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 251.3 kB/s eta 0:00:00 kB/s eta 0:00:01:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.8/47.8 kB 268.1 kB/s eta 0:00:00 kB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.7/259.7 MB 4.7 MB/s eta 0:00:00m eta 0:00:010:00:02m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 1.8 MB/s eta 0:00:00MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 1.2 MB/s eta 0:00:003.1 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 5.6 MB/s eta 0:00:00m eta 0:00:01:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 4.1 MB/s eta 0:00:00m eta 0:00:010:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 3.0 MB/s eta 0:00:003.1 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 4.5 MB/s eta 0:00:00m eta 0:00:010:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.6/393.6 kB 1.5 MB/s eta 0:00:00m eta 0:00:010:01:01
   ━━━━━━━━━━━━━━━━

In [70]:
import tensorflow as tf
import numpy as np

fashion_mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

print(f"training images shape: {train_images.shape}, training label shape: {train_labels.shape}")
print(f"test images shape: {test_images.shape}, test label shape: {test_labels.shape}")

training images shape: (60000, 28, 28), training label shape: (60000,)
test images shape: (10000, 28, 28), test label shape: (10000,)


In [16]:
print(train_images[5:])
print(train_labels[:5])

[[[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ... 180   0   0]
  [  0   0   0 ...  72   0   0]
  [  0   0   0 ...  70   0   0]]

 ...

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0  

In [29]:
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy

In [82]:
model = Sequential(
    [
        Dense(28 * 28, activation='relu'),
        Dense(100, activation='relu'),
        Dense(10, activation='linear')
    ]
)

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss=SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy']
)

m = train_images.shape[0]
flattend_images = tf.reshape(train_images, (m,-1))
print(f"sample size: {m}")
print(f"flattened data shape: {flattend_images.shape}")

model.fit(
    flattend_images, train_labels,
    epochs=10
)

sample size: 60000
flattened data shape: (60000, 784)
Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - accuracy: 0.6519 - loss: 8.4784
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.6780 - loss: 0.8842
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - accuracy: 0.7053 - loss: 0.7646
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.7579 - loss: 0.6337
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.8061 - loss: 0.5646
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.8342 - loss: 0.4949
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - accuracy: 0.8491 - loss: 0.4587
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.8535 - loss: 0.4384
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.8625 - loss: 0.4094
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - accuracy: 0.8705 - loss: 0.3787


In [83]:
m_test = test_images.shape[0]
flattened_test_images = tf.reshape(test_images, (m_test,-1))
logits = model.predict(flattened_test_images)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [86]:
probabilities = tf.nn.softmax(logits)
print(f"probabilities shpae: {probabilities.shape}")
print(probabilities[5:])
predicts = tf.math.argmax(probabilities, axis=1).numpy()
print(f"predicst shape: {predicts.shape}")
print("first 5 predicts", predicts[5:])
print("first 5 ground truth", test_labels[5:])
tp = tf.where(predicts == test_labels, 1, 0)
print(tp)

evaluation = model.evaluate(flattened_test_images, test_labels, verbose=2, return_dict=True)
print(evaluation)
# print(f"loss: {test_loss}, accuracy: {test_acc}")

probabilities shpae: (10000, 10)
tf.Tensor(
[[3.50803472e-19 9.99999702e-01 1.57004693e-25 ... 0.00000000e+00
  4.14305942e-18 0.00000000e+00]
 [1.04849346e-01 1.61670425e-04 2.13422388e-01 ... 8.50417869e-09
  7.21529173e-03 9.71161924e-08]
 [1.56830140e-07 4.77090605e-22 1.32135358e-02 ... 6.73208624e-37
  1.33588390e-10 6.34310143e-30]
 ...
 [8.91503071e-33 0.00000000e+00 4.88739240e-29 ... 0.00000000e+00
  9.99999940e-01 2.24214252e-34]
 [4.85770943e-21 9.99999821e-01 2.66870508e-31 ... 0.00000000e+00
  3.33613753e-17 0.00000000e+00]
 [4.69563600e-17 5.18909760e-09 5.84306903e-35 ... 6.49950430e-02
  4.99190401e-06 3.37752234e-03]], shape=(9995, 10), dtype=float32)
predicst shape: (10000,)
first 5 predicts [1 6 6 ... 8 1 5]
first 5 ground truth [1 4 6 ... 8 1 5]
tf.Tensor([1 1 1 ... 1 1 1], shape=(10000,), dtype=int32)
313/313 - 0s - 905us/step - accuracy: 0.8526 - loss: 0.4541
{'accuracy': 0.8525999784469604, 'loss': 0.4540776014328003}
